import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { Document, Types } from 'mongoose';

export type DailyReportDocument = DailyReport & Document<Types.ObjectId>;

// _id defaults to true (Mongoose auto-generates one per subdocument) — this
// is what makes a task individually addressable for PATCH /tasks/:id
// (the To-Do/EOD Trello board), not just an array-index-only embedded item.
@Schema()
export class DailyReportTask {
  _id: Types.ObjectId;

  @Prop({ required: true }) title: string;
  @Prop({ required: true, enum: ['urgent', 'high', 'medium', 'low'] })
  priority: 'urgent' | 'high' | 'medium' | 'low';
  @Prop() category?: string;
  @Prop({ default: false }) isOverdue: boolean;
  // Workflow progress — orthogonal to priority/isOverdue (urgency metadata).
  // Moving a task to 'done' never touches isOverdue/priority.
  @Prop({ required: true, enum: ['todo', 'in_progress', 'done'], default: 'todo' })
  status: 'todo' | 'in_progress' | 'done';

  // ---- Optional per-task attribution (additive) ----
  // Set only when python-agent's report-extraction step ties a task to a
  // specific record it was given in its research context (never invented —
  // see anthropic_client.py's REPORT_EXTRACTION_SYSTEM_PROMPT). Resolved to
  // assignedUserId deterministically in dashboard.service.ts's
  // recordDailyReport() via a direct Deal/Quote model lookup; a task with
  // neither field resolvable simply stays unassigned/shared, exactly like
  // every task did before this was added.
  @Prop() relatedDealId?: string;
  @Prop() relatedQuoteId?: string;
  // The raw Outlook message id (EmailIntelligenceItem.externalMessageId),
  // not that item's own Mongo _id — see dashboard.service.ts's attributeTask
  // for why the lookup is keyed this way.
  @Prop() relatedEmailId?: string;
  @Prop({ index: true }) assignedUserId?: string;
}
const DailyReportTaskSchema = SchemaFactory.createForClass(DailyReportTask);

// Structured counterpart to the free-form chat conversations the scheduled
// morning/EOD job already creates per user — one doc per (agentId,
// reportType, date), not one per user, so the dashboard shows a single
// business-wide status per agent rather than N duplicate rows. NestJS owns
// all writes here (python-agent only structures text, doesn't persist).
@Schema({ timestamps: true, collection: 'daily_reports' })
export class DailyReport {
  // Without this, two orgs both using the built-in 'store_manager' persona
  // would collide on the same (agentId, reportType, date) document — agentId
  // alone stopped being globally unique the moment AgentRole/CHAT_AGENTS
  // personas became shared concepts across tenants.
  @Prop({ required: true, index: true }) organizationId: string;
  // Without this, two stores in the same org both scheduling the built-in
  // 'store_manager' persona's EOD/morning run would upsert onto the same
  // (organizationId, agentId, reportType, date) document, silently
  // overwriting each other's report. Optional only for the type — every
  // write path (store-settings.service.ts's runForStore) always has a store
  // in hand and always sets it.
  @Prop({ index: true }) storeId?: string;
  @Prop({ required: true, index: true }) agentId: string;
  @Prop({ required: true, enum: ['morning', 'eod'] }) reportType: 'morning' | 'eod';
  @Prop({ required: true, index: true }) date: string; // "YYYY-MM-DD"

  @Prop({ type: [DailyReportTaskSchema], default: [] }) tasks: DailyReportTask[];
  @Prop({ default: '' }) summary: string;

  @Prop({ required: true }) sourceConversationId: string;
  // Audit only — whose reply was structured (see store-settings.service.ts's
  // "first successful user" selection for the exactly-once-per-day design).
  @Prop({ required: true }) sourceUserId: string;

  // True when this report was generated by the cron's catch-up path (the
  // scheduled trigger window was missed, e.g. the process was down) rather
  // than on time — surfaced on the Owner/Manager dashboards and mirrored as
  // a `daily_report_missed` TimelineEvent + notification.
  @Prop({ default: false }) wasMissed: boolean;

  // ---- Automatic EOD email tracking (additive) ----
  // Mirrors the status/sentAt/error pattern already used by
  // email-follow-up-reminder.schema.ts's draftStatus. This report document's
  // own _id (already unique) is the idempotency key for "has this been
  // emailed yet" — store-settings.service.ts checks emailStatus before
  // sending, so a cron re-run/restart never re-sends. Only ever set for
  // reportType:'eod' — morning reports are left at the 'pending' default and
  // never dispatched.
  @Prop({ enum: ['pending', 'sent', 'failed'], default: 'pending' })
  emailStatus: 'pending' | 'sent' | 'failed';
  @Prop() emailSentAt?: Date;
  @Prop() emailError?: string;

  createdAt: Date;
  updatedAt: Date;
}

export const DailyReportSchema = SchemaFactory.createForClass(DailyReport);
DailyReportSchema.index(
  { organizationId: 1, storeId: 1, agentId: 1, reportType: 1, date: 1 },
  { unique: true },
);
